# Generated by Django 3.1.5 on 2021-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='list',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listid',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
