# Generated by Django 3.1.5 on 2021-02-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_final_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listid',
        ),
    ]
