# Generated by Django 3.1.5 on 2021-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_watchlist_listid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
